### ISSUE TITLE
Initial CUB Tuning Infrastructure

### ISSUE THREAD

**Issue by senior-zero** [NVIDIA/cub#631]
CUB Tuning Infrastructure

Some of the CUB algorithms have to be re-tuned for the recent architectures. Apart from that, tuning is rarely final. Functional changes, like the support of 64-bit offsets, lead to arbitrary performance changes and imply periodic re-tuning. To continue providing SOL performance, we must automate CUB tuning as much as possible. 

On the other hand, tuning infrastructure would allow us to explain tuning decisions to users and facilitate them in contributing valuable use cases directly to our set of performance-critical workloads. 

We'll use this issue as a root for the whole tuning infrastructure development. Preliminary steps include:
```[tasklist]
### Tasks
- [x] Develop a tuneable benchmark format
- [x] Develop a configuration space description
- [x] Develop a tuning storage format
- [x] Develop automation scripts for covering configuration spaces
- [x] Develop analysis automation scripts for optimal tuning selection
- [x] Write a workload contribution guide
```
